apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - secret.enc.yaml
  - oauth-secret.enc.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - loadgen-cronjob.yaml
  - frontend-deployment.yaml
