apiVersion: v1
kind: Secret
metadata:
    name: kubepets-oauth
    namespace: kubepets
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:hC1JAAWZh9WIzplk8MXdH4L5/QbgYgT1EHpVd2y5cgSkGuXEk75JGj2B+xto2xG/HypW+K0eLE2/QIx59oH/pgIklYP71k4A,iv:GvlZqjcRnRlB69j4ycsMqwT6OYUqkZyY8XTA8jJIbv8=,tag:00ALZNezbzN1dclSz8lScA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:ZFiGSBnktHWO9CnUs2q4K+cjoqMsWTUgIc4oA0P+khUycbk=,iv:wc0WC8OLeAPRnzPr37C/vKDSdfCNqUnt/h8cxQMeJ7s=,tag:SAeh2usEECzl6k5DDgSQRg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/2OtMt1AHkN0f/5nI2w/tPQ340imcXm2tviZre1aFOxLUfICCnK1F4T3MH2goUQeUnH6byyFsAtLuPjRwUOQhQ==,iv:9xn6yxUx/lqYsg++atOS+VOWQPJ3CnEzj4G7rjN2gDA=,tag:un3DVLmaa5NIeodoPuoFLQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZsSy2pwVfKtr9Cb1I9UfkToqMGA0RkBXB7UDmsAP7oi50W8n,iv:q20u5bX6g2qb2MWKojyDNxjJ7xbQy5MJxYv5nG2dF84=,tag:kPI6vzYRAsiI7+0PuVpPfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydU02dnRWcWFvSzFKdE8x
            eW51S0Ftb0QyZGIxNGMzV1BGaUR1cmFUK2xBClo1THpqNno2NnV0THpIOThGUmtO
            K3cvaDZYd2FFN1BPcythOU81RWVxZlUKLS0tIGk1V1VJaUxZK010TGM0U1dSVUJN
            SUVTRHQ3V0U5cTh2Y0k3RFFKV2Fna2sKG812siOncBW3Mk50Cl3BeFOlGYXQl6Ko
            WS5RikAwf6pE1o8wUnjyO3TWOMlWhw0k3B0+x0f06IYM4PcLDSktaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tzqrp2703ca6se8vpq99rmvjhu2e3ulzntaemelgz0q0vmjq65qsjk85kg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T16:48:56Z"
    mac: ENC[AES256_GCM,data:Dix81lzKPxqANGLqlO6SIaOpbblpG+VzYUHCCHwp7K6MdhAMmyD6Bovu1oE9kg5c26rpTrx2S6l7MMMhIgkIYb48++lwrI1qBokfTGmNpO1bKGftrVVSu+X5HaGFXx+FWBqZMjxfTZUiH7QA0S7LoepE+uqwTw16z0ADsotLsQM=,iv:9e/0Ed/x6N+tu+CwRP8MJyD9/muQE1Ggk1y+TV0nGXA=,tag:hlJnH0X2na9j1Nsuz/Mi4w==,type:str]
    version: 3.13.2
