apiVersion: v1
kind: Secret
metadata:
    name: kubepets-oauth
    namespace: kubepets
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Tf4VVK0RB2OSkQRFFm4D0JBqVr0QjraqkxFVpvjUF7aWmxqCJw==,iv:+qHzX4XfyWlg4QitqE5DgaXyvNBc0cxZknvNFx5F59E=,tag:aA2/dv8yat2xS7Q+T9gDxA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:JVauZm6taVP9+Q==,iv:sSN2Wv0lof9Sh//N97hYTsuS3RbkVVNKD9eOor+BsGc=,tag:PWQVBslBSYyljOgwDd0qWg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/2OtMt1AHkN0f/5nI2w/tPQ340imcXm2tviZre1aFOxLUfICCnK1F4T3MH2goUQeUnH6byyFsAtLuPjRwUOQhQ==,iv:9xn6yxUx/lqYsg++atOS+VOWQPJ3CnEzj4G7rjN2gDA=,tag:un3DVLmaa5NIeodoPuoFLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydU02dnRWcWFvSzFKdE8x
            eW51S0Ftb0QyZGIxNGMzV1BGaUR1cmFUK2xBClo1THpqNno2NnV0THpIOThGUmtO
            K3cvaDZYd2FFN1BPcythOU81RWVxZlUKLS0tIGk1V1VJaUxZK010TGM0U1dSVUJN
            SUVTRHQ3V0U5cTh2Y0k3RFFKV2Fna2sKG812siOncBW3Mk50Cl3BeFOlGYXQl6Ko
            WS5RikAwf6pE1o8wUnjyO3TWOMlWhw0k3B0+x0f06IYM4PcLDSktaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tzqrp2703ca6se8vpq99rmvjhu2e3ulzntaemelgz0q0vmjq65qsjk85kg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T16:00:02Z"
    mac: ENC[AES256_GCM,data:/Dy0qESapxlJsHjPKv+VfFQD8J86JIw6IPvE2u+htrPkYdgtBCPgF1lu3Popy5z8kqexQW9UAzmRD6g4eZNO99WrCr10jHjUkOd8XYH1HkjqW6XwjEyJirL1dhdvQhB3qx6lRLv+sgvLOkgUVL/BrYORIAZDVJ+2isJVeSGX1pI=,iv:ojK+OK56Mp60tGGRiOOPoiA2zVquYEf8AGUtTx4F2oU=,tag:UFZ2SpFLNiI9NdKIJDwE1g==,type:str]
    version: 3.13.2
