apiVersion: v1
kind: Secret
metadata:
    name: kubepets-oauth
    namespace: kubepets
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Tf4VVK0RB2OSkQRFFm4D0JBqVr0QjraqkxFVpvjUF7aWmxqCJw==,iv:+qHzX4XfyWlg4QitqE5DgaXyvNBc0cxZknvNFx5F59E=,tag:aA2/dv8yat2xS7Q+T9gDxA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:JVauZm6taVP9+Q==,iv:sSN2Wv0lof9Sh//N97hYTsuS3RbkVVNKD9eOor+BsGc=,tag:PWQVBslBSYyljOgwDd0qWg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/2OtMt1AHkN0f/5nI2w/tPQ340imcXm2tviZre1aFOxLUfICCnK1F4T3MH2goUQeUnH6byyFsAtLuPjRwUOQhQ==,iv:9xn6yxUx/lqYsg++atOS+VOWQPJ3CnEzj4G7rjN2gDA=,tag:un3DVLmaa5NIeodoPuoFLQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZsSy2pwVfKtr9Cb1I9UfkToqMGA0RkBXB7UDmsAP7oi50W8n,iv:q20u5bX6g2qb2MWKojyDNxjJ7xbQy5MJxYv5nG2dF84=,tag:kPI6vzYRAsiI7+0PuVpPfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydU02dnRWcWFvSzFKdE8x
            eW51S0Ftb0QyZGIxNGMzV1BGaUR1cmFUK2xBClo1THpqNno2NnV0THpIOThGUmtO
            K3cvaDZYd2FFN1BPcythOU81RWVxZlUKLS0tIGk1V1VJaUxZK010TGM0U1dSVUJN
            SUVTRHQ3V0U5cTh2Y0k3RFFKV2Fna2sKG812siOncBW3Mk50Cl3BeFOlGYXQl6Ko
            WS5RikAwf6pE1o8wUnjyO3TWOMlWhw0k3B0+x0f06IYM4PcLDSktaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tzqrp2703ca6se8vpq99rmvjhu2e3ulzntaemelgz0q0vmjq65qsjk85kg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T20:58:14Z"
    mac: ENC[AES256_GCM,data:WLikiRNbW935TeonIBa8ZX9pzmy8ZyzcRasqxi1pWtK6SdFTYg9rJNClON+NvwsIw9xdCgv5SNc0t/sUBiIGqoA9n5vxg4t0sYYO4VivANibKb37HPUq3YmhjayOsLoGHc8FqUqUAtA9/RWpeBw9+xIp5edvE7+q0EhN1yxvhyc=,iv:1DLR0iwxYI6q73uQW4YhojSSdpyR/3ygUDhHZbu+byk=,tag:89d6mn+7DOO/Ua8hXc9zMA==,type:str]
    version: 3.13.2
