apiVersion: v1
kind: Secret
metadata:
    name: kubepets-db
    namespace: kubepets
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:fbr97tS8/Oc=,iv:tQy1tFhs0Pg1j96ZHEdz1xT+1bFxy6AAvkUi03Yj4b4=,tag:sWboHyqG9fs+4K5aWJ/rBw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:D1HHhvsiy7g=,iv:IQfM8Wc7GPpFrKL6WDbCfJ5DFaS28QEDhcWGNr6PXDc=,tag:cJ4cF3NES605iuB/4e6rkw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NvkeY3LICYlLKfikSFU2xc3Z0n+P9ULO1WNkmVfw,iv:/Gnrqtl5UdgFw+yzq8Fzt9vZo0y9JaysooTryIpogB0=,tag:dcnwH4odE+/etActYBEQgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWi9qdTAwdStLeU9JbjZN
            NU5UcnFXaVhYbk1kRHlsQlpuYXhNY2tHNFQ4CmE5RnJaYUIrSHhpeWprQm1XYkIv
            bG9wdW4rMXNLaUd3WC8vZFJ3RzZZN3MKLS0tIEJxWGNnWjl4blkycXlKY2dPdDFP
            dUgvWlF6TDFaV3ZTNlRsWkJHdmltVzQKdT1vCYH/4ZpoIpcvi8Lu/G5Xoexmjld5
            nTBegbOerFlKTGvVB539aNhcyuqzFo0VxdYpwT8VYcd9IWoLJe+Fvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tzqrp2703ca6se8vpq99rmvjhu2e3ulzntaemelgz0q0vmjq65qsjk85kg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T19:09:20Z"
    mac: ENC[AES256_GCM,data:Ybh/75t0wxok98/Tr7bEo0khGxt34D25ptEy9oTQbP+RReEduU9b8CKk8tzBln6jjMVZ3v5sg5r/HqgFYeNHo5q7wpZJp2jaRncMRdtN8bsYRDYKewZEYOsQJvaZximXQFBtyAfafQ4JwNjqQ2GwSf8tnZG5FgrC2SzPDj50aJs=,iv:+jYkZQQqafNjjzRxXVtPrVRSHET9YB2DEITWzImWO5U=,tag:2xSLLa/c/7jemCMtbhFwug==,type:str]
    version: 3.13.2
