apiVersion: v1
kind: ServiceAccount
metadata:
  name: noc-port-forward
  namespace: headlamp
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-port-forward-token
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: noc-port-forward
type: kubernetes.io/service-account-token
