apiVersion: v1
kind: Secret
metadata:
    name: sops-test-secret
    namespace: default
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:mLBPHhsZxBEWtYG9aK6m06sEAr7hQDcvj2FeRJr16jywHw==,iv:lPiXTYLZYKcDTWTNunN3YCsYvE0m2ztxiUy7VEIQJy8=,tag:VFVg13yr8zFEdnrDWPkLjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ckZUT0dqR1VCRFNnQVd6
            dnY2SGVPc0V3YlBSUm95Q21uTDl6MFBzc2tBClRHOEFWVHU1Z1Fpc0NLdk1EU09O
            bE12Tm1DdVVjRTJGVmIrc2I1cm1UZUkKLS0tIHFEWk90SndoaU5JK2Q2dGRQanU4
            TjFMQVp0cDErSlJaeEcrYVRCUFg0bncK9eu2nT2vLaaz8V7LMuXED/MTywo357+9
            HMTScc2GCzuYaZhYA9iSD38NlvTAC6gxH4Tw/A18DU8y9rRZ05cV0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tzqrp2703ca6se8vpq99rmvjhu2e3ulzntaemelgz0q0vmjq65qsjk85kg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T15:21:19Z"
    mac: ENC[AES256_GCM,data:9XJw5W6l+RvgO+aK4VcD3NfCOU5SGJaex10NnBEyef3DfIxgVUDQbh5sy+X2as6f2XaJgDGUzpq+iXSh7qZmmRk6/2E4DxdCGWUph8GM9DEEPrNMhBs5lhMEVlj5Ux4+qHzPipN+kvZUmDOD7jIphFuXhu+3xqnI5fRukbiMcrU=,iv:yMiJGRizV2V6/N8zg8Yv6dQQDWAu1KD4bJ5UyM2dtkk=,tag:v/u4QjtmUEiFIcBk2mtXPw==,type:str]
    version: 3.13.2
