// Codegen: converts the raw hand-drawn SVG assets under src/components/icons/
// into typed React components in src/components/icons/generated/.
//
// Re-run after dropping new/updated assets:  node scripts/generate-icons.mjs
//
// Transformations applied to each asset:
//   - strip <title>/<desc> (decorative in-app; cards carry their own a11y text)
//   - strip full-size background <rect>s (white paper would wreck the dark theme)
//   - normalize ink fills (#000/#000000) -> currentColor so Tailwind text-*
//     classes tint the artwork
//   - kebab-case attrs -> JSX camelCase (fill-rule/clip-rule)
//   - emit a component spreading SVGProps<SVGSVGElement> (className included)
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..", "src", "components", "icons");
const sources = [
  join(root, "creature_svg_files"),
  join(root, "creepy_eye_svgs_selected"),
];
const outDir = join(root, "generated");
mkdirSync(outDir, { recursive: true });

function pascalCase(name) {
  return name
    .replace(/\.svg$/, "")
    .split(/[-_.]/)
    .filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join("");
}

function convert(file) {
  const raw = readFileSync(file, "utf8");

  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${file}: no viewBox`);
  // Preserve an explicit root fill (some assets set fill="none" and give every
  // path its own fill); default the rest to currentColor so paths relying on
  // SVG's default black ink inherit the tint instead.
  const rootFill = raw.match(/<svg[^>]*?\sfill="([^"]+)"/)?.[1] ?? "currentColor";

  let inner = raw.slice(raw.indexOf(">", raw.indexOf("<svg")) + 1, raw.lastIndexOf("</svg>"));
  inner = inner
    .replace(/<title[^>]*>[\s\S]*?<\/title>/g, "")
    .replace(/<desc[^>]*>[\s\S]*?<\/desc>/g, "")
    .replace(/<rect[^>]*\/>/g, "") // all rects in these assets are paper bgs
    .replace(/fill="#000(000)?"/g, 'fill="currentColor"')
    .replace(/fill-rule=/g, "fillRule=")
    .replace(/clip-rule=/g, "clipRule=")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => `      ${l}`)
    .join("\n");

  const name = pascalCase(basename(file));
  return {
    name,
    code: `// AUTO-GENERATED by scripts/generate-icons.mjs from ${basename(file)} - do not edit by hand.
import type { SVGProps } from "react";

export default function ${name}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="${rootFill}" aria-hidden {...props}>
${inner}
    </svg>
  );
}
`,
  };
}

const exports_ = [];
for (const dir of sources) {
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".svg")).sort()) {
    const { name, code } = convert(join(dir, f));
    writeFileSync(join(outDir, `${name}.tsx`), code);
    exports_.push(name);
    console.log(`generated ${name}.tsx`);
  }
}

writeFileSync(
  join(outDir, "index.ts"),
  `// AUTO-GENERATED by scripts/generate-icons.mjs - do not edit by hand.\n` +
    exports_.map((n) => `export { default as ${n} } from "./${n}";`).join("\n") +
    "\n",
);
console.log(`index.ts: ${exports_.length} components`);
